import { initContract } from "@ts-rest/core";
import {
  AgentsSendMessageRequestSchema,
  AgentsUiInterruptResponseSchema,
  AgentsUiSendMessageResponseSchema,
  AgentsUiWorktreeConversationResponseSchema,
  AgentIdParamsSchema,
  AgentListResponseSchema,
  AgentResponseSchema,
  AppConfigSchema,
  AvailableBranchesQuerySchema,
  BranchListResponseSchema,
  CiLogsResponseSchema,
  CreateTabResponseSchema,
  CreateWorktreeRequestSchema,
  CreateWorktreeResponseSchema,
  OpenWorktreeRequestSchema,
  EnabledResponseSchema,
  ErrorResponseSchema,
  OkResponseSchema,
  ProjectSnapshotSchema,
  PullMainRequestSchema,
  PullMainResponseSchema,
  RunIdParamsSchema,
  UpsertCustomAgentRequestSchema,
  ValidateCustomAgentResponseSchema,
  SendWorktreePromptRequestSchema,
  SetWorktreeArchivedRequestSchema,
  SetWorktreeArchivedResponseSchema,
  PostWorktreeToLinearRequestSchema,
  PostWorktreeToLinearResponseSchema,
  ProjectWorktreeSnapshotSchema,
  SetWorktreeLabelRequestSchema,
  SetWorktreeLabelResponseSchema,
  ToggleEnabledRequestSchema,
  WorktreeDiffResponseSchema,
  WorktreeListResponseSchema,
  WorktreeNameParamsSchema,
  WorktreeTabParamsSchema,
  NotificationIdParamsSchema,
  LinearIssuesResponseSchema,
  AutoNameConfigResponseSchema,
  InstancesResponseSchema,
  ProjectsResponseSchema,
  AddProjectRequestSchema,
  AddProjectResponseSchema,
  ProjectInitsResponseSchema,
  ProjectPrefixParamsSchema,
  MigrateProjectsRequestSchema,
  MigrateProjectsResponseSchema,
} from "./schemas";

const c = initContract();

export const apiPaths = {
  fetchConfig: "/api/config",
  fetchAvailableBranches: "/api/branches",
  fetchBaseBranches: "/api/base-branches",
  fetchProject: "/api/project",
  fetchAgents: "/api/agents",
  createAgent: "/api/agents",
  updateAgent: "/api/agents/:id",
  deleteAgent: "/api/agents/:id",
  validateAgent: "/api/agents/validate",
  attachAgentsWorktreeConversation: "/api/agents/worktrees/:name/attach",
  fetchAgentsWorktreeConversationHistory: "/api/agents/worktrees/:name/history",
  sendAgentsWorktreeConversationMessage: "/api/agents/worktrees/:name/messages",
  interruptAgentsWorktreeConversation: "/api/agents/worktrees/:name/interrupt",
  streamAgentsWorktreeConversation: "/ws/agents/worktrees/:name",
  fetchWorktrees: "/api/worktrees",
  createWorktree: "/api/worktrees",
  removeWorktree: "/api/worktrees/:name",
  openWorktree: "/api/worktrees/:name/open",
  closeWorktree: "/api/worktrees/:name/close",
  refreshWorktreeAgentTerminal: "/api/worktrees/:name/agent-terminal/refresh",
  setWorktreeArchived: "/api/worktrees/:name/archive",
  syncWorktreePrs: "/api/worktrees/:name/sync-prs",
  postWorktreeToLinear: "/api/worktrees/:name/linear/post",
  setWorktreeLabel: "/api/worktrees/:name/label",
  sendWorktreePrompt: "/api/worktrees/:name/send",
  createWorktreeTab: "/api/worktrees/:name/tabs",
  selectWorktreeTab: "/api/worktrees/:name/tabs/:tabId/select",
  deleteWorktreeTab: "/api/worktrees/:name/tabs/:tabId",
  mergeWorktree: "/api/worktrees/:name/merge",
  fetchWorktreeDiff: "/api/worktrees/:name/diff",
  fetchLinearIssues: "/api/linear/issues",
  fetchAutoNameConfig: "/api/project/auto-name",
  setLinearAutoCreate: "/api/linear/auto-create",
  setAutoRemoveOnMerge: "/api/github/auto-remove-on-merge",
  pullMain: "/api/pull-main",
  fetchCiLogs: "/api/ci-logs/:runId",
  dismissNotification: "/api/notifications/:id/dismiss",
  fetchInstances: "/api/instances",
  fetchProjects: "/api/projects",
  addProject: "/api/projects",
  projectInits: "/api/projects/init",
  migrateProjects: "/api/projects/migrate",
  removeProject: "/api/projects/:prefix",
} as const;

const commonErrorResponses = {
  400: ErrorResponseSchema,
  404: ErrorResponseSchema,
  409: ErrorResponseSchema,
  500: ErrorResponseSchema,
  502: ErrorResponseSchema,
  503: ErrorResponseSchema,
} as const;

export const apiContract = c.router({
  fetchConfig: {
    method: "GET",
    path: apiPaths.fetchConfig,
    responses: {
      200: AppConfigSchema,
    },
  },
  fetchAvailableBranches: {
    method: "GET",
    path: apiPaths.fetchAvailableBranches,
    query: AvailableBranchesQuerySchema,
    responses: {
      200: BranchListResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchBaseBranches: {
    method: "GET",
    path: apiPaths.fetchBaseBranches,
    responses: {
      200: BranchListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchProject: {
    method: "GET",
    path: apiPaths.fetchProject,
    responses: {
      200: ProjectSnapshotSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  fetchAgents: {
    method: "GET",
    path: apiPaths.fetchAgents,
    responses: {
      200: AgentListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  createAgent: {
    method: "POST",
    path: apiPaths.createAgent,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  updateAgent: {
    method: "PUT",
    path: apiPaths.updateAgent,
    pathParams: AgentIdParamsSchema,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  deleteAgent: {
    method: "DELETE",
    path: apiPaths.deleteAgent,
    pathParams: AgentIdParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  validateAgent: {
    method: "POST",
    path: apiPaths.validateAgent,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: ValidateCustomAgentResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  attachAgentsWorktreeConversation: {
    method: "POST",
    path: apiPaths.attachAgentsWorktreeConversation,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAgentsWorktreeConversationHistory: {
    method: "GET",
    path: apiPaths.fetchAgentsWorktreeConversationHistory,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendAgentsWorktreeConversationMessage: {
    method: "POST",
    path: apiPaths.sendAgentsWorktreeConversationMessage,
    pathParams: WorktreeNameParamsSchema,
    body: AgentsSendMessageRequestSchema,
    responses: {
      200: AgentsUiSendMessageResponseSchema,
      ...commonErrorResponses,
    },
  },
  interruptAgentsWorktreeConversation: {
    method: "POST",
    path: apiPaths.interruptAgentsWorktreeConversation,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: AgentsUiInterruptResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktrees: {
    method: "GET",
    path: apiPaths.fetchWorktrees,
    responses: {
      200: WorktreeListResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  createWorktree: {
    method: "POST",
    path: apiPaths.createWorktree,
    body: CreateWorktreeRequestSchema,
    responses: {
      201: CreateWorktreeResponseSchema,
      ...commonErrorResponses,
    },
  },
  removeWorktree: {
    method: "DELETE",
    path: apiPaths.removeWorktree,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  openWorktree: {
    method: "POST",
    path: apiPaths.openWorktree,
    pathParams: WorktreeNameParamsSchema,
    body: OpenWorktreeRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  closeWorktree: {
    method: "POST",
    path: apiPaths.closeWorktree,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  refreshWorktreeAgentTerminal: {
    method: "POST",
    path: apiPaths.refreshWorktreeAgentTerminal,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeArchived: {
    method: "PUT",
    path: apiPaths.setWorktreeArchived,
    pathParams: WorktreeNameParamsSchema,
    body: SetWorktreeArchivedRequestSchema,
    responses: {
      200: SetWorktreeArchivedResponseSchema,
      ...commonErrorResponses,
    },
  },
  postWorktreeToLinear: {
    method: "POST",
    path: apiPaths.postWorktreeToLinear,
    pathParams: WorktreeNameParamsSchema,
    body: PostWorktreeToLinearRequestSchema,
    responses: {
      200: PostWorktreeToLinearResponseSchema,
      ...commonErrorResponses,
    },
  },
  syncWorktreePrs: {
    method: "POST",
    path: apiPaths.syncWorktreePrs,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: ProjectWorktreeSnapshotSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeLabel: {
    method: "PUT",
    path: apiPaths.setWorktreeLabel,
    pathParams: WorktreeNameParamsSchema,
    body: SetWorktreeLabelRequestSchema,
    responses: {
      200: SetWorktreeLabelResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendWorktreePrompt: {
    method: "POST",
    path: apiPaths.sendWorktreePrompt,
    pathParams: WorktreeNameParamsSchema,
    body: SendWorktreePromptRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  createWorktreeTab: {
    method: "POST",
    path: apiPaths.createWorktreeTab,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      201: CreateTabResponseSchema,
      ...commonErrorResponses,
    },
  },
  selectWorktreeTab: {
    method: "POST",
    path: apiPaths.selectWorktreeTab,
    pathParams: WorktreeTabParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  deleteWorktreeTab: {
    method: "DELETE",
    path: apiPaths.deleteWorktreeTab,
    pathParams: WorktreeTabParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  mergeWorktree: {
    method: "POST",
    path: apiPaths.mergeWorktree,
    pathParams: WorktreeNameParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktreeDiff: {
    method: "GET",
    path: apiPaths.fetchWorktreeDiff,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: WorktreeDiffResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchLinearIssues: {
    method: "GET",
    path: apiPaths.fetchLinearIssues,
    responses: {
      200: LinearIssuesResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  fetchAutoNameConfig: {
    method: "GET",
    path: apiPaths.fetchAutoNameConfig,
    responses: {
      200: AutoNameConfigResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  setLinearAutoCreate: {
    method: "PUT",
    path: apiPaths.setLinearAutoCreate,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  setAutoRemoveOnMerge: {
    method: "PUT",
    path: apiPaths.setAutoRemoveOnMerge,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  pullMain: {
    method: "POST",
    path: apiPaths.pullMain,
    body: PullMainRequestSchema,
    responses: {
      200: PullMainResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchCiLogs: {
    method: "GET",
    path: apiPaths.fetchCiLogs,
    pathParams: RunIdParamsSchema,
    responses: {
      200: CiLogsResponseSchema,
      ...commonErrorResponses,
    },
  },
  dismissNotification: {
    method: "POST",
    path: apiPaths.dismissNotification,
    pathParams: NotificationIdParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
  },
  fetchInstances: {
    method: "GET",
    path: apiPaths.fetchInstances,
    responses: {
      200: InstancesResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchProjects: {
    method: "GET",
    path: apiPaths.fetchProjects,
    responses: {
      200: ProjectsResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  addProject: {
    method: "POST",
    path: apiPaths.addProject,
    body: AddProjectRequestSchema,
    responses: {
      200: AddProjectResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  projectInits: {
    method: "GET",
    path: apiPaths.projectInits,
    responses: {
      200: ProjectInitsResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  migrateProjects: {
    method: "POST",
    path: apiPaths.migrateProjects,
    body: MigrateProjectsRequestSchema,
    responses: {
      200: MigrateProjectsResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  removeProject: {
    method: "DELETE",
    path: apiPaths.removeProject,
    pathParams: ProjectPrefixParamsSchema,
    body: c.noBody(),
    responses: {
      200: OkResponseSchema,
      404: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
}, {
  strictStatusCodes: true,
});
