services:
  - name: BE
    portEnv: DASHBOARD_PORT
  - name: FE
    portEnv: FRONTEND_PORT

profiles:
  default:
    name: default

linkedRepos:
  - repo: centdix/workmux-test-linked
    alias: linked